### ISSUE TITLE
ValueError : operands could not be broadcast together with shapes (2,2,2) (2,2,3)

### ISSUE THREAD

**Issue by Baahman** [CtheSky/Coursera-Deep-Learning-Specialization#1]
After implementing the conv_forward function in the coursera's week 4 convolution model step_by_step assignment i'm getting the ValueError that operands could not be broadcast together with shapes (2,2,2)
(2,2,3)
I've copied the code from your repository and still getting the error
![screenshot 27](https://user-images.githubusercontent.com/28726602/34974487-5711b770-fab3-11e7-89fb-9b58cacdeb01.png)

**Comment by CtheSky** [comment]
`np.multiply` does element-wise multiplication, so it's complaining about the different shape of `a_slice_prev` and `W`. To implement it correctly, you should do a matrix multiplication by `np.dot(a_slice_prev, W)` or `a_slice_prev * W` in `conv_single_step` function.

I keep notebooks here only for backup since I don't have access to these after the course is over. For more questions, you should use the course forum where there are more people ready to help you.
